package com.example.rentakucapstone.dataKendaraan

enum class MerkMobil(val value: String) {
    ASTON_MARTIN("aston martin"),
    BMW("bmw"),
    CADILLAC("cadillac"),
    CHEVROLET("chevrolet"),
    CHRYSLER("chrysler"),
    DAIHATSU("daihatsu"),
    FORD("ford"),
    HONDA("honda"),
    HYUNDAI("hyundai"),
    ISUZU("isuzu"),
    JAGUAR("jaguar"),
    JEEP("jeep"),
    KIA("kia"),
    LAND_ROVER("land rover"),
    LEXUS("lexus"),
    MAZDA("mazda"),
    MERCEDES_BENZ("mercedes-benz"),
    MG("mg"),
    MINI("mini"),
    MITSUBISHI("mitsubishi"),
    NISSAN("nissan"),
    PEUGEOT("peugeot"),
    PORSCHE("porsche"),
    RENAULT("renault"),
    SKODA("skoda"),
    SSANGYONG("ssangyong"),
    SUBARU("subaru"),
    SUZUKI("suzuki"),
    TOYOTA("toyota"),
    VOLKSWAGEN("volkswagen")

}
